spring.application.name=motos-control-api

# ==============================
# DATABASE CONFIG (RAILWAY)
# ==============================
spring.datasource.url=jdbc:postgresql://${PGHOST:${POSTGRE_HOST}}:${PGPORT:${POSTGRE_PORT}}/${PGDATABASE:${POSTGRE_DB}}
spring.datasource.username=${PGUSER:${POSTGRE_USER}}
spring.datasource.password=${PGPASSWORD:${POSTGRE_PASSWORD}}
spring.flyway.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==============================
# GOOGLE LOGIN CONFIG
# ==============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=https://motos-control-api-production.up.railway.app/login/oauth2/code/google

# ==============================
# ADMIN CONFIG
# ==============================
app.admin.emails=${APP_ADMIN_EMAILS}
